authenticate/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.loginUsr, name='login'),
    path('login/', views.loginUsr, name='login'),
    path('logout/', views.logoutFunc, name='logout'),
    path('signup/', views.signUp, name='signup'),
]

ppw_story/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story_one.urls')),
    path('authenticate/', include('authenticate.urls')),
]

story_one/urls.py
from django.urls import path
from . import views

app_name = 'story_one'
urlpatterns = [
    path('', views.home_view, name="profile"),
    path('profile/', views.profile, name="profile"),
    path('gallery/', views.gallery, name="gallery"),
    path('schedule/', views.schedule, name="schedule"),
    path('schedule/<int:id_>/', views.delete, name="delete"),
    path('schedule/<int:id_>/detail', views.detail, name='detail'),
    path('events/', views.events, name="events"),
    path('events/apply/<int:id_>', views.apply, name="apply"),
    path('books/', views.books, name="books"),
    path('data/', views.books_data, name="data"),
] 

authenticate/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserData(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, primary_key=True)

story_one/models.py
from django.db import models

# Create your models here.
class Schedule(models.Model):
    subject = models.CharField(max_length = 50)
    lecturer = models.CharField(max_length = 50)
    room = models.CharField(max_length = 50)
    credit = models.CharField(max_length = 10)
    term = models.CharField(max_length = 20)
    description = models.CharField(max_length = 60)

class Events(models.Model):
    event = models.CharField(max_length = 50)
    day = models.CharField(max_length = 10)
    date = models.CharField(max_length = 50)
    time = models.CharField(max_length = 50)
    place = models.CharField(max_length = 50)
    def __str__ (self):
        return self.event

class EventsParticipants(models.Model):
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=100)
    eventName = models.ForeignKey(Events, on_delete=models.CASCADE)
    def __str__ (self):
        return self.name

authenticate/forms.py
from django import forms

class loginForm(forms.Form):
    username = forms.CharField(label="Username" , widget=forms.TextInput(attrs={
        'class': 'form-control',
        'type': 'text',
        'title': 'Username',
        'placeholder': 'Plese enter your username',
        'required': True,
    }))
    password = forms.CharField(label="Password", widget=forms.TextInput(attrs={
        'class': 'form-control',
        'type': 'password',
        'placeholder': 'Plese enter your password',
        'required': True,
    }))

story_one/forms.py
from django import forms
from .models import Schedule, Events, EventsParticipants
from django.forms import ModelForm

class Schedule_Form(forms.ModelForm):
    class Meta:
	    model = Schedule
	    fields = '__all__'
	    error_messages = {
		    'required' : 'Please Type'
	    }

class Events_Form(forms.ModelForm):
	class Meta:
		model = Events
		fields = '__all__'
		error_messages = {
			'required' : 'Please Type'
		}

class Applicants_Form(forms.ModelForm):
	class Meta:
		model = EventsParticipants
		fields = ['name','email']
		error_messages = {
			'required' : 'Please Type'
		}

authenticate/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from .forms import *
from .models import *

# Create your views here.

def loginUsr(request):
    form = loginForm()
    userData = None
    if(request.method == "POST"):
        form = loginForm(request.POST)
        if(form.is_valid()):
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if(user is not None):
                login(request, user)
                userData = UserData.objects.filter(user=user)
                if(len(userData) > 0):
                    response = {'form': form, 'userData': userData[0]}
                    return render(request, 'login.html', response)
                else:
                    response = {'form': form}
                    return render(request, 'login.html', response)
            else:
                messages = ['Incorrect username or password']
                response = {'form': form, 'messages': messages}
                return render(request, 'login.html', response)
    else:
        user = request.user
        if(user.is_authenticated):
            userData = UserData.objects.filter(user=user)
            if(len(userData) > 0):
                response = {'form': form, 'userData': userData[0]}
                return render(request, 'login.html', response)
            else:
                response = {'form': form}
                return render(request, 'login.html', response)
        else:
            response = {'form': form}
            return render(request, 'login.html', response)


def signUp(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/authenticate/login/')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})

def logoutFunc(request):
    logout(request)
    return redirect('/authenticate/login/')

story_one/views.py
from django.shortcuts import render
from .models import Schedule, Events, EventsParticipants
from .forms import Schedule_Form, Events_Form, Applicants_Form
from django.http import HttpResponseRedirect, JsonResponse
import json
import requests


def home_view(request):
	return render(request, "profile.html")

def profile(request):
	return render(request, "profile.html")

def gallery(request):
	return render(request, "gallery.html")

def schedule(request):
	schedules = Schedule.objects.all()
	form = Schedule_Form(request.POST or None)
	content = {
		'form' : form,
		'schedules' : schedules
	}
	if (form.is_valid and request.method == 'POST'):
		form.save()
		form.cleaned_data['subject']
		return HttpResponseRedirect(request.path_info, content)
	return render(request, "schedule.html", content)

def detail(request, id_=None):
	try:
		subDesc = Schedule.objects.get(id = id_)
		context = {'subDesc' : subDesc}
		return render(request, 'subjectDetail.html', context)
	except Exception:
		return HttpResponseRedirect('/schedule')

def delete(request, id_=None):
	content = Schedule.objects.filter(id = id_)
	content.delete()
	return HttpResponseRedirect('/schedule')

def events(request):
	events = Events.objects.all()
	applicants = EventsParticipants.objects.all()
	form = Events_Form(request.POST or None)
	content = {
		'form' : form,
		'events' : events,
		'applicants' : applicants
	}
	if (request.method == 'POST'):
		form = Events_Form(request.POST)
		if form.is_valid() :
			form.save()
			form.cleaned_data['event']
		return HttpResponseRedirect(request.path_info, content)
	return render(request, "events.html", content)

def apply (request, id_):
	if (request.method == 'POST'):
		form = Applicants_Form(request.POST)
		print("post")
		if form.is_valid():
			print("valid")
			form = EventsParticipants(eventName = Events.objects.get(id = id_), name = form.data['name'], email= form.data['email'])
			form.save()
		return HttpResponseRedirect('/events/')
	else :
		form = Applicants_Form()
		print("get")
		applyEve = Events.objects.get(id = id_)
		context = {
			'form' : form,
			'applyEve' : applyEve
		}	
	return render(request, "applyEvent.html", context)

def books(request): 
	return render(request, "searchBook.html")

def books_data(request):
	url = "https://www.googleapis.com/books/v1/volumes?q=" + request.GET['q']
	ret = requests.get(url)
	data = 	json.loads(ret.content)
	return JsonResponse(data, safe=False)

authenticate/templates/login.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<link rel="stylesheet" type="text/css" href="{% static 'css/login1.css' %}" />
<style>
    .form-group {
  margin-bottom: 38px;
}

.sect-title {
  font-weight: 700;
  font-size: 25px;
  line-height: 37.5px;
  margin-bottom: 15px;
  color: #000000;
}

.form,
.sect-title {
  display: flex;
  flex-direction: column;
  align-items: center;
}

.submission {
    display: flex;
    justify-content: center;
}

#id_username,
#id_password {
  width: 410px;
  height: 54px;
  font-weight: 400;
  text-align: left;
  font-size: 23px;
  display: flex;
  align-items: center;
  padding-left: 1rem;
}

button {
  width: 200px;
  height: 47px;
  background-color: #000;
  border-radius: 15.4315px;
  border: none;
  font-size: 20px;
  font-weight: 700;
  display: flex;
  align-items: center;
  justify-content: center;
  color: white;
  font-family: "Poppins", sans-serif;
}

button:hover {
  cursor: pointer;
  background-color: #ffffff;
  border: 1px black solid;
  color: #000;
}

.toSign {
    margin-top: 5rem;
}
</style>
{% endblock %} {% block title %} dionisiusamudra | login {% endblock %} {% block content %}
<div class="page-title">
    <div class="text">LogIn</div>
    <div class="mini-text">ログイン</div>
</div>
<div style="display: flex; justify-content: center; width: 100%; height: 60vh; align-items: center;">

{% if user.is_authenticated %}
    <div class="container" style="margin-top: 4vh; margin-bottom: 3vh;">
        <h3 class='display-5'>Have a wonderful day,</h3>
        <h2 class="display-4" id="username-display">
            {{user.username}}
        </h2>
    </div>
    <div class="centre-items tombol">
        <a class="btn custom-button" href="{% url 'logout' %}" id='logout'>Logout</a>
    </div>

{% else %}
    <div class='form'>
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <div class="sect-title">
                    User Name: 
                </div>
                <div class="insert">
                    {{ form.username }}
                </div>
            </div>
            <div class="form-group">
                <div class="sect-title">
                    Password: 
                </div>
                <div class="insert">
                    {{ form.password }}
                </div>
            </div>
            <div class="submission">        
                <button type="submit">LogIn</button>
            </div>
        </form>
        <div class="toSign">
        Don't have an account? Sign up <a href="{% url 'signup' %}" style="color: rgb(148, 148, 148);" id="sign-up">here</a>!
        </div>
    </div>
{% endif %}
</div>
{% endblock %}

authenticate/templates/signup.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<style>
    .form-group {
  margin-bottom: 38px;
}

.sect-title {
  font-weight: 700;
  font-size: 25px;
  line-height: 37.5px;
  margin-bottom: 15px;
  color: #000000;
}

.form,
.sect-title {
  display: flex;
  flex-direction: column;
  align-items: center;
}

.submission {
    display: flex;
    justify-content: center;
}

#id_username,
#id_password1,
#id_password2 {
  width: 410px;
  height: 54px;
  font-weight: 400;
  text-align: left;
  font-size: 23px;
  display: flex;
  align-items: center;
  padding-left: 1rem;
}

button {
  width: 200px;
  height: 47px;
  background-color: #000;
  border-radius: 15.4315px;
  border: none;
  font-size: 20px;
  font-weight: 700;
  display: flex;
  align-items: center;
  justify-content: center;
  color: white;
  font-family: "Poppins", sans-serif;
  margin: 0 !important;
}

#submit-button {
    margin: 0 !important;
}

button:hover {
  cursor: pointer;
  background-color: #ffffff;
  border: 1px black solid;
  color: #000;
}

.toSign {
    margin-top: 5rem;
}
</style>
{% endblock %} {% block title %} dionisiusamudra | signup {% endblock %} {% block content %}
<div class="page-title">
    <div class="text">SignUp</div>
    <div class="mini-text">サインアップ</div>
</div>
<div style="display: flex; justify-content: center; width: 100%; height: 60vh; align-items: center;">


    <div class='form'>
        <form method="post">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
                <div class="insert">
                    <div class="fieldWrapper">
                        {{ field.errors }}
                        {{ field }}
                    </div>
                </div>
            </div>
            {% endfor %}
            <button type="submit" id="submit-button">Sign up</button>
        </form>
    </div>
</div>
<div class="description">
    <ul>
        <li>Baris pertama adalah Username</li>
        <li>Baris kedua adalah Password</li>
        <li>Baris ketiga adalah Retype Password</li>
    </ul>
</div>
{% endblock %}

story_one/templates/applyEvent.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/applyEvent.css' %}"
/>
{% endblock %} {% block title %}
dionisiusamudra | schedule detail {% endblock %}
<!-- -->
{% block content %}
<div class="detail-container" style="height: 75vh; display: flex; flex-direction: column; justify-content: center; align-items: center;">
    <div class="detail-title" style=" margin-bottom: 2.5rem;">{{ applyEve.event }}</div>
    <form class="addSchedule" action="#" method="POST">
      {% csrf_token %} {{ form.as_table }}
      <input type="submit" value="ADD" />
    </form>
</div> 
{% endblock %}

story_one/templates/events.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/events.css' %}"
/>
{% endblock %} {% block title %} dionisiusamudra | events {% endblock %}
<!-- -->
{% block content %}
<div class="page-title">
  <div class="text">Events</div>
  <div class="mini-text">イベント</div>
</div>
<div style="display: flex; justify-content: center; width: 100%;">
<div class="schedContainer">
  {% if events %}
  <!---->
  {% for event in events %}
  <div class="mainCard">
    <div class="innerCard">
      <div>
        <div class="card-title">{{ event.event }}</div>
        <div class="card-detail">{{ event.day }}</div>
        <div class="card-detail">{{ event.date }}</div>
        <div class="card-detail">{{ event.time }}</div>
        <div class="card-detail">{{ event.place }}</div>
      </div>
      <div class="participants">
        {% if applicants %}
        <div class="appli-title">
          Participants
        </div>
          {% for applicant in applicants %}
            {% if applicant.eventName == event %}
              <div>{{ applicant.name }}</div>
            {% endif %}
          {% endfor %}
        {% endif %}
      </div>
      <div class="button" style="display: flex">
        <div class="detail" style="width: 100%; display: flex; justify-content: center">
          <a style="width: 100%; text-align: center;" href="apply/{{event.id}}" role="button"> Apply </a>
        </div>
      </div>
    </div>
  </div>
  {% endfor %} {% endif %}
  <div class="mainCard">
    <div class="innerCard">
      <form class="addSchedule" action="/events/" method="POST">
        {% csrf_token %} {{ form.as_table }}
        <input type="submit" value="ADD" />
      </form>
    </div>
  </div>
</div>
</div>
{% endblock %}

story_one/templates/gallery.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<link rel="stylesheet" type="text/css" href="{% static 'css/gallery.css' %}" />
{% endblock %} {% block title %} dionisiusamudra | gallery {% endblock %}
<!-- -->
{% block content %}
<div class="page-title">
  <div class="text">Gallery</div>
  <div class="mini-text">ギャラリー</div>
</div>
<div class="galleryContainer">
  <div class="photos">
    <div class="image">
      <img width="100%;" src="{% static 'images/gallery/s1.jpg'%}" />
    </div>
    <div class="image">
      <img width="100%;" src="{% static 'images/gallery/p2k.JPG'%}" />
    </div>
    <div class="image">
      <img width="100%;" src="{% static 'images/gallery/l3.JPG'%}" />
    </div>
    <div class="image">
      <img width="100%;" src="{% static 'images/gallery/s4.jpg'%}" />
    </div>
    <div class="image">
      <img width="100%;" src="{% static 'images/gallery/p5.jpeg'%}" />
    </div>
    <div class="image">
      <img width="100%;" src="{% static 'images/gallery/l6.JPG'%}" />
    </div>
    <div class="image">
      <img width="100%;" src="{% static 'images/gallery/s7.jpg'%}" />
    </div>
    <div class="image">
      <img width="100%;" src="{% static 'images/gallery/p8k.JPG'%}" />
    </div>
    <div class="image">
      <img width="100%;" src="{% static 'images/gallery/l9.jpg'%}" />
    </div>
  </div>
  <div class="photos">
    <div class="image">
      <img width="100%;" src="{% static 'images/gallery/p1.jpeg'%}" />
    </div>
    <div class="image">
      <img width="100%;" src="{% static 'images/gallery/l2.JPG'%}" />
    </div>
    <div class="image">
      <img width="100%;" src="{% static 'images/gallery/s3.jpg'%}" />
    </div>
    <div class="image">
      <img width="100%;" src="{% static 'images/gallery/p4k.JPG'%}" />
    </div>
    <div class="image">
      <img width="100%;" src="{% static 'images/gallery/l5.JPG'%}" />
    </div>
    <div class="image">
      <img width="100%;" src="{% static 'images/gallery/s6.jpg'%}" />
    </div>
    <div class="image">
      <img width="100%;" src="{% static 'images/gallery/p7.jpg'%}" />
    </div>
    <div class="image">
      <img width="100%;" src="{% static 'images/gallery/l8.JPG'%}" />
    </div>
    <div class="image">
      <img width="100%;" src="{% static 'images/gallery/s9.jpg'%}" />
    </div>
  </div>
  <div class="photos">
    <div class="image">
      <img width="100%;" src="{% static 'images/gallery/l1.JPG'%}" />
    </div>
    <div class="image">
      <img width="100%;" src="{% static 'images/gallery/s2.jpg'%}" />
    </div>
    <div class="image">
      <img width="100%;" src="{% static 'images/gallery/p3k.JPG'%}" />
    </div>
    <div class="image">
      <img width="100%;" src="{% static 'images/gallery/l4.JPG'%}" />
    </div>
    <div class="image">
      <img width="100%;" src="{% static 'images/gallery/s5.jpg'%}" />
    </div>
    <div class="image">
      <img width="100%;" src="{% static 'images/gallery/p6.jpg'%}" />
    </div>
    <div class="image">
      <img width="100%;" src="{% static 'images/gallery/l7.JPG'%}" />
    </div>
    <div class="image">
      <img width="100%;" src="{% static 'images/gallery/s8.jpg'%}" />
    </div>
    <div class="image">
      <img width="100%;" src="{% static 'images/gallery/p9k.JPG'%}" />
    </div>
  </div>
</div>
{% endblock %}

story_one/templates/schedule.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/schedule1.css' %}"
/>
{% endblock %} {% block title %} dionisiusamudra | schedule {% endblock %}
<!-- -->
{% block content %}
<div class="page-title">
  <div class="text">Schedules</div>
  <div class="mini-text">スケジュール</div>
</div>
<div style="display: flex; justify-content: center; width: 100%;">
<div class="schedContainer">
  {% if schedules %}
  <!---->
  {% for schedule in schedules %}
  <div class="mainCard">
    <div class="innerCard">
      <div>
        <div class="card-title">{{ schedule.subject }}</div>
        <div class="card-detail">{{ schedule.lecturer }}</div>
        <div class="card-detail">{{ schedule.room }}</div>
        <div class="card-detail">{{ schedule.credit }}</div>
        <div class="card-detail">{{ schedule.term }}</div>
      </div>
      <div class="button" style="display: flex">
        <div
          class="detail"
          style="width: 100%; display: flex; justify-content: center"
        >
          <a  style="width: 100%; text-align: center;" href="{{schedule.id}}/detail" role="button"> Detail </a>
        </div>
        <div
          class="erase"
          style="width: 100%; display: flex; justify-content: center"
        >
          <a style="width: 100%; text-align: center;" href="{{schedule.id}}/" role="button"> Erase </a>
        </div>
      </div>
      <!---->
    </div>
  </div>
  {% endfor %} {% endif %}
  <div class="mainCard">
    <div class="innerCard">
      <form class="addSchedule" action="/schedule/" method="POST">
        {% csrf_token %} {{ form.as_table }}
        <input type="submit" value="ADD" />
      </form>
    </div>
  </div>
</div>
</div>
{% endblock %}

story_one/templates/searchBook.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/searchBook.css' %}"
/>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% endblock %} {% block title %} dionisiusamudra | schedule {% endblock %}
<!-- -->
{% block content %}
<div class="page-title">
  <div class="text">Book Search</div>
  <div class="mini-text">本の検索</div>
</div>
<div class="search-box">
    <input id="book-keyword" placeholder="search"/>
    <table id="book-table">
    </table>
</div>




{% endblock %}
{% block script %}
<script type="text/javascript">
    $("#book-keyword").keyup(function(){
        var usr_input = $("#book-keyword").val();
        $.ajax({
            url: "/data?q=" + usr_input,
            success: function(data) {
                var books_array = data.items;
                $("#book-table").empty();
                if(usr_input != ""){
                $("#book-table").append("<tr><th> No. </th><th> Cover </th><th> Title </th><th> Author </th><th> Year </th></tr>");
                }
                for (i = 0; i < books_array.length; i++){
                    var title = books_array[i].volumeInfo.title;
                    var images = books_array[i].volumeInfo.imageLinks.thumbnail;
                    var author = books_array[i].volumeInfo.authors;
                    var year = books_array[i].volumeInfo.publishedDate;
                    $("#book-table").append("<tr><th>" + i+1 + ".</th><td><img src=" + images + "/></td><td>" + title + "</td><td>" + author + "</td><td>" + year + "</td></tr>");
                }
            }
        });
    })
</script>
{% endblock %}

story_one/templates/subjectDetail.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/subjectDetail.css' %}"
/>
{% endblock %} {% block title %}
dionisiusamudra | schedule detail {% endblock %}
<!-- -->
{% block content %}
<div class="detail-container">
  <div class="detail-title">{{ subDesc.subject }}</div>

  <table>
    <tr>
      <td class="left-table">Lecturer :</td>
      <td class="right-table">{{subDesc.lecturer}}</td>
    </tr>
    <tr>
      <td class="left-table">Room :</td>
      <td class="right-table">{{subDesc.room}}</td>
    </tr>
    <tr>
      <td class="left-table">Credits :</td>
      <td class="right-table">{{subDesc.credit}}</td>
    </tr>
    <tr>
      <td class="left-table">Terms :</td>
      <td class="right-table">{{subDesc.term}}</td>
    </tr>
    <tr>
      <td class="left-table">Description :</td>
      <td class="right-table">{{subDesc.description}}</td>
    </tr>
  </table>
</div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    {% block meta %}{% endblock %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />
    <link
      href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800&display=swap"
      rel="stylesheet"
    />
    <script src="{% static 'js/navbar.js' %}"></script>
    <title>{% block title %}dionisiusamudra{% endblock %}</title>
  </head>
  <body>
    <div id="pop-nav" class="pop-nav">
      <div class="close-button">
        <img
          class="close"
          onclick="closeNav()"
          src="{% static 'images/160171083747624487.png'%}"
          width="30px"
          height="30px"
        />
      </div>
      <div class="pop-menu-container">
        <a
          href="{% url 'story_one:profile' %}"
          class="pop-menu"
          onclick="closeNav()"
          >Profile</a
        >
        <a
          href="{% url 'story_one:schedule' %}"
          class="pop-menu"
          onclick="closeNav()"
          >Schedule</a
        >
        <a
        href="{% url 'story_one:events' %}"
        class="pop-menu"
        onclick="closeNav()"
        >Events</a
        >
        <a
          href="{% url 'story_one:gallery' %}"
          class="pop-menu"
          onclick="closeNav()"
          >Gallery</a
        >
        <a
        href="{% url 'story_one:books' %}"
        class="pop-menu"
        onclick="closeNav()"
        >Books</a
      >
      </div>
    </div>
    <div class="navbar">
      <div class="left">
        <div class="logo">
          <a href="{% url 'story_one:profile' %}">DS</a>
        </div>
      </div>
      <div class="right">
        <div class="right-nav">
          <a class="profile" href="{% url 'story_one:profile' %}">Profile</a>
        </div>
        <div class="right-nav">
          <a class="others" href="{% url 'story_one:schedule' %}">Schedule</a>
        </div>
        <div class="right-nav">
          <a class="others" href="{% url 'story_one:events' %}">Events</a>
        </div>
        <div class="right-nav">
          <a class="gallery" href="{% url 'story_one:gallery' %}">Gallery</a>
        </div>
        <div class="right-nav">
          <a class="gallery" href="{% url 'story_one:books' %}">Books</a>
        </div>
        <div class="burger" onclick="openNav()">
          <img
            src="{% static 'images/1200px-Hamburger_icon.svg.webp'%}"
            width="35px"
            height="35px"
          />
        </div>
      </div>
    </div>
    <div class="main-container">
      <div class="main">{% block content %}{% endblock content %}</div>
    </div>
    {% block script %}{% endblock %}
    <footer>
      <a
        target="_blank"
        rel="noopener noreferrer"
        href="https://id.linkedin.com/in/dionisius-baskoro-samudra-678ab7193"
      >
        <img
          class="contact"
          src="{% static 'images/PinClipart.com_zig-zag-clipart_1003028.png'%}"
        />
      </a>
      <a
        target="_blank"
        rel="noopener noreferrer"
        href="https://www.instagram.com/dionisiusamudra/"
      >
        <img class="contact" src="{% static 'images/pngguru.com.png'%}" />
      </a>
      <a href="#">
        <div class="logo2">DS</div>
      </a>
      <a
        target="_blank"
        rel="noopener noreferrer"
        href="https://steamcommunity.com/profiles/76561198255063738/"
      >
        <img class="contact" src="{% static 'images/steam-logo-white.png'%}" />
      </a>
      <a
        target="_blank"
        rel="noopener noreferrer"
        href="https://twitter.com/maritubir_?s=09"
        class="contact"
      >
        <img
          class="contact"
          src="{% static 'images/Twitter_Logo_White_On_Image_Cropped.png'%}"
          width="2rem"
          height="2rem"
        />
      </a>
    </footer>

  </body>
</html>